- name: Launch frontend container
  community.docker.docker_container:
    name: frontend
    image: artzerrr/tp-devops-frontend:latest
    state: started
    restart_policy: always
    pull: true
    restart: yes
    networks:
      - name: app-network
    ports:
      - "80:80"