services:

  database:
    build: ./database
    container_name: postgresql
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./simple-api/simpleapi/simpleapi
    container_name: simple-api
    depends_on:
      - database
    expose:
      - "8080"
    networks:
      - app-network

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg-data: