name: Continuous Integration

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-and-analyze:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build, test and analyze with Maven & SonarCloud
        run: >
          mvn -B verify sonar:sonar
          -Dsonar.projectKey=Artzerr_tp-devops
          -Dsonar.organization=artzerr
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          --file simple-api/simpleapi/simpleapi/pom.xml