# Le nom de votre pipeline, qui apparaîtra sur GitHub
name: CI DevOps 2025

# Les déclencheurs : QUAND ce pipeline doit-il s'exécuter ?
on:
  # À chaque push sur les branches 'main' ou 'develop'
  push:
    branches: [ "main", "develop" ]
  # Aussi à chaque fois qu'une Pull Request est ouverte ou mise à jour
  pull_request:

# Les "jobs" : QUE FAIT ce pipeline ?
jobs:
  # On définit un job qu'on nomme 'test-backend'
  test-backend:
    # La machine virtuelle sur laquelle ce job va tourner
    runs-on: ubuntu-24.04

    # La séquence d'étapes à exécuter
    steps:
      # Étape 1: Récupérer le code de votre dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Installer Java (JDK 21) sur la machine virtuelle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3: Lancer la commande Maven pour compiler et tester
      - name: Build and test with Maven
        # -B = Batch mode (non-interactif)
        # --file = Spécifie le chemin vers le pom.xml de notre API
        run: mvn -B clean verify --file simple-api/pom.xml